### ISSUE TITLE
Publish to Terraform registry?

### ISSUE THREAD

**Issue by lizthegrey** [DeviaVir/terraform-provider-gsuite#133]
Hey, is there a reason this provider isn't in the official https://registry.terraform.io/?

**Comment by DeviaVir** [comment]
We are mentioned here: https://www.terraform.io/docs/providers/index.html?_ga=2.24612794.1442278123.1585728314-310612550.1585155993

I don't think it is possible to publish a provider to that registry at this time, is it?

**Comment by lizthegrey** [comment]
It is, you just need to sign into https://registry.terraform.io/github/create

**Comment by DeviaVir** [comment]
This only let's me create a `module`, not a provider.

**Comment by lizthegrey** [comment]
https://www.terraform.io/docs/registry/providers/docs.html says it's in closed beta, _but_ if you already appear on https://www.terraform.io/docs/providers/type/community-index.html I think they'll let you in?

**Comment by yordis** [comment]
Hey @apparentlymart could you give us a hand with this?

**Comment by DeviaVir** [comment]
Sounds like Hashicorp is not in a place to accept more providers at this time. I'll let you know if I hear more.

**Comment by apparentlymart** [comment]
Hi all,

I'm not directly involved in the Terraform Registry side of this -- that's a separate team -- but I gather that while publishing providers in the registry is still in a closed beta, you can request to join that beta by going to the provider publishing section of the registry UI (after logging in with GitHub) and following some instructions to contact the Terraform Registry team.

With that said, currently that UI will just tell you to email terraform-registry-beta@hashicorp.com, so the other avenue is to just email that address directly for more information. There are some limitations for the moment due to it still being in beta, but I'll leave the registry team to explain those details.

Thanks!

**Comment by DeviaVir** [comment]
Thank you @apparentlymart looks like we're all set here: https://registry.terraform.io/providers/DeviaVir/gsuite/latest
